server:
  port: 80

spring:
  datasource:
    url: jdbc:mariadb://database-1.cgqsli5o96gd.ap-northeast-2.rds.amazonaws.com:3306/ongshop
    username: admin
    password: admin#$%
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace