server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true
  profiles:
    include: db, jwt, cloudinary

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    root: info